name: Clonar Pasta do GitHub

on:
  workflow_dispatch:

jobs:
  copy-folder:
    runs-on: ubuntu-latest
    
    # Adicione estas permissões para permitir o push no repositório
    permissions:
      contents: write

    steps:
      - name: Checkout do seu repositório
        uses: actions/checkout@v4

      - name: Baixar apenas a pasta src do PicoUSB
        run: |
          # Inicializa um repositório temporário e configura o sparse-checkout
          mkdir temp_repo && cd temp_repo
          git init
          git remote add origin https://github.com/TomBrlek/PicoUSB.git
          git config core.sparseCheckout true
          
          # Define qual pasta você quer baixar
          echo "src/" >> .git/info/sparse-checkout
          
          # Baixa apenas o histórico recente da branch main
          git pull origin main --depth=1
          
          # Retorna para a raiz e move a pasta src para o destino desejado
          cd ..
          mkdir -p pico-usb-src
          cp -r temp_repo/src/* pico-usb-src/
          
          # Remove a pasta temporária
          rm -rf temp_repo

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add pico-usb-src/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza arquivos da pasta src do PicoUSB" && git push)
